### ISSUE TITLE
Update documentation script to filter out unused artifacts

### ISSUE THREAD

**Issue by wwilsman** [bigtestjs/meta#3]
The current obvious thing to remove is the `package:undefined` entry. Without adding any filters to the website, it renders this entry into the sidebar (see https://bigtestjs.io/docs/convergence).

It may also be useful to investigate the `.json` output and scrub other potentially unnecessary things. But for now, this is the only thing that's visible that could be removed.

**Comment by Robdel12** [comment]
Closed with #7
